/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fox.gltf --transform
Author: Alexei Ostapenko (https://sketchfab.com/alexanders823)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fox-4e37c303f8a241aaa2511bd9f3019273
Title: Fox
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export  default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fox-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={2.94}>
          <group name="601576fce4814617ab1896d47107c82ffbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="SK_Fox" rotation={[-Math.PI / 2, 0, 0]}>
                  <group name="root001">
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.M_Fox} skeleton={nodes.Object_48.skeleton} />
                      <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.M_Fox} skeleton={nodes.Object_49.skeleton} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fox-transformed.glb')
